# Generated by Django 5.0.3 on 2024-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStoreApp', '0005_book_price_currency_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
